DROP DATABASE IF EXISTS `E-Banking`;
CREATE DATABASE IF NOT EXISTS `E-Banking`; 
USE `E-Banking`;

CREATE TABLE `Users` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NOT NULL,
	`HashPassword` VARCHAR(30) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `Name` (`Name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `Accounts` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`FkID` INT UNSIGNED NOT NULL,
	`AccountNumber` VARCHAR(9) NOT NULL,
	`Amount` DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `AccountNumber` (`AccountNumber`),
	FOREIGN KEY (`FkID`) REFERENCES `E-Banking`.`Users`(`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `Payments` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`FkIDAccountOwner` INT UNSIGNED NOT NULL,
	`FkIDAccountRecipient` int UNSIGNED NOT NULL,
	`Amount` DECIMAL(10,2) NOT NULL,
	`DatePay` DATETIME NOT NULL,
	`InformationTransmitted` VARCHAR(100) NOT NULL,
	`PersonalInformation` VARCHAR(350) NOT NULL,
	PRIMARY KEY (`ID`),
    FOREIGN KEY (`FkIDAccountOwner`) REFERENCES `E-Banking`.`Accounts`(`ID`),
	FOREIGN KEY (`FKIDAccountRecipient`) REFERENCES `E-Banking`.`Accounts`(`ID`)		
	) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;